name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BUN_ENV: production
      FORCE_COLOR: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Tools
        uses: asdf-vm/actions/install@v3

      - name: Install
        run: bun install

      - name: Build
        run: bun run build --filter='./apps/docs'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          publish_dir: ./apps/docs/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
